### ISSUE TITLE
`v0.10.1` is not a valid semantic tag name! Skipping

### ISSUE THREAD

**Issue by mxcl** [fischerscode/tagger#7]
Does this action only work if we don’t use `v` prefixes?

https://github.com/teaxyz/setup/actions/runs/3839408151/jobs/6537131573#step:3:30

**Comment by fischerscode** [comment]
Just set `prefix: v`. Then it should work.
```yaml
- uses: fischerscode/tagger@v0.1 
  with: 
   # The prefix of the semantic tags.
   # Default: '' 
   prefix: v
```
